// flow-typed signature: 7ba2a08ef9610b48a79f1ff473c321a2
// flow-typed version: <<STUB>>/binpacking_v~0.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'binpacking'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'binpacking' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'binpacking/js/demo' {
  declare module.exports: any;
}

declare module 'binpacking/js/index' {
  declare module.exports: any;
}

declare module 'binpacking/js/jquery' {
  declare module.exports: any;
}

declare module 'binpacking/js/packer.growing' {
  declare module.exports: any;
}

declare module 'binpacking/js/packer' {
  declare module.exports: any;
}

declare module 'binpacking/node-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'binpacking/js/demo.js' {
  declare module.exports: $Exports<'binpacking/js/demo'>;
}
declare module 'binpacking/js/index.js' {
  declare module.exports: $Exports<'binpacking/js/index'>;
}
declare module 'binpacking/js/jquery.js' {
  declare module.exports: $Exports<'binpacking/js/jquery'>;
}
declare module 'binpacking/js/packer.growing.js' {
  declare module.exports: $Exports<'binpacking/js/packer.growing'>;
}
declare module 'binpacking/js/packer.js' {
  declare module.exports: $Exports<'binpacking/js/packer'>;
}
declare module 'binpacking/node-test.js' {
  declare module.exports: $Exports<'binpacking/node-test'>;
}
