// flow-typed signature: 11fd6b9e51a10f44dccd0caa81703adc
// flow-typed version: <<STUB>>/mustache_v~0.7.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mustache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mustache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mustache/mustache' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/ampersand_escape' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/apostrophe' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/array_of_strings' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/backslashes' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/bug_11_eating_whitespace' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/changing_delimiters' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/check_falsy' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/comments' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/complex' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/context_lookup' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/delimiters' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/disappearing_whitespace' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/dot_notation' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/double_render' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/empty_list' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/empty_sections' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/empty_string' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/empty_template' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/error_not_found' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/escaped' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/falsy' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/grandparent_context' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/higher_order_sections' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/included_tag' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/inverted_section' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/keys_with_questionmarks' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/malicious_template' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/multiline_comment' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/nested_dot' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/nested_higher_order_sections' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/nested_iterating' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/nesting_same_name' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/nesting' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/null_string' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/null_view' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/partial_array_of_partials_implicit' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/partial_array_of_partials' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/partial_array' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/partial_empty' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/partial_template' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/partial_view' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/partial_whitespace' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/recursion_with_same_names' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/reuse_of_enumerables' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/section_as_context' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/simple' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/string_as_context' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/two_in_a_row' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/two_sections' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/unescaped' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/whitespace' {
  declare module.exports: any;
}

declare module 'mustache/test/_files/zero_view' {
  declare module.exports: any;
}

declare module 'mustache/test/context-test' {
  declare module.exports: any;
}

declare module 'mustache/test/helper' {
  declare module.exports: any;
}

declare module 'mustache/test/mustache-spec-test' {
  declare module.exports: any;
}

declare module 'mustache/test/parse-test' {
  declare module.exports: any;
}

declare module 'mustache/test/render-test' {
  declare module.exports: any;
}

declare module 'mustache/test/scanner-test' {
  declare module.exports: any;
}

declare module 'mustache/test/writer-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mustache/mustache.js' {
  declare module.exports: $Exports<'mustache/mustache'>;
}
declare module 'mustache/test/_files/ampersand_escape.js' {
  declare module.exports: $Exports<'mustache/test/_files/ampersand_escape'>;
}
declare module 'mustache/test/_files/apostrophe.js' {
  declare module.exports: $Exports<'mustache/test/_files/apostrophe'>;
}
declare module 'mustache/test/_files/array_of_strings.js' {
  declare module.exports: $Exports<'mustache/test/_files/array_of_strings'>;
}
declare module 'mustache/test/_files/backslashes.js' {
  declare module.exports: $Exports<'mustache/test/_files/backslashes'>;
}
declare module 'mustache/test/_files/bug_11_eating_whitespace.js' {
  declare module.exports: $Exports<'mustache/test/_files/bug_11_eating_whitespace'>;
}
declare module 'mustache/test/_files/changing_delimiters.js' {
  declare module.exports: $Exports<'mustache/test/_files/changing_delimiters'>;
}
declare module 'mustache/test/_files/check_falsy.js' {
  declare module.exports: $Exports<'mustache/test/_files/check_falsy'>;
}
declare module 'mustache/test/_files/comments.js' {
  declare module.exports: $Exports<'mustache/test/_files/comments'>;
}
declare module 'mustache/test/_files/complex.js' {
  declare module.exports: $Exports<'mustache/test/_files/complex'>;
}
declare module 'mustache/test/_files/context_lookup.js' {
  declare module.exports: $Exports<'mustache/test/_files/context_lookup'>;
}
declare module 'mustache/test/_files/delimiters.js' {
  declare module.exports: $Exports<'mustache/test/_files/delimiters'>;
}
declare module 'mustache/test/_files/disappearing_whitespace.js' {
  declare module.exports: $Exports<'mustache/test/_files/disappearing_whitespace'>;
}
declare module 'mustache/test/_files/dot_notation.js' {
  declare module.exports: $Exports<'mustache/test/_files/dot_notation'>;
}
declare module 'mustache/test/_files/double_render.js' {
  declare module.exports: $Exports<'mustache/test/_files/double_render'>;
}
declare module 'mustache/test/_files/empty_list.js' {
  declare module.exports: $Exports<'mustache/test/_files/empty_list'>;
}
declare module 'mustache/test/_files/empty_sections.js' {
  declare module.exports: $Exports<'mustache/test/_files/empty_sections'>;
}
declare module 'mustache/test/_files/empty_string.js' {
  declare module.exports: $Exports<'mustache/test/_files/empty_string'>;
}
declare module 'mustache/test/_files/empty_template.js' {
  declare module.exports: $Exports<'mustache/test/_files/empty_template'>;
}
declare module 'mustache/test/_files/error_not_found.js' {
  declare module.exports: $Exports<'mustache/test/_files/error_not_found'>;
}
declare module 'mustache/test/_files/escaped.js' {
  declare module.exports: $Exports<'mustache/test/_files/escaped'>;
}
declare module 'mustache/test/_files/falsy.js' {
  declare module.exports: $Exports<'mustache/test/_files/falsy'>;
}
declare module 'mustache/test/_files/grandparent_context.js' {
  declare module.exports: $Exports<'mustache/test/_files/grandparent_context'>;
}
declare module 'mustache/test/_files/higher_order_sections.js' {
  declare module.exports: $Exports<'mustache/test/_files/higher_order_sections'>;
}
declare module 'mustache/test/_files/included_tag.js' {
  declare module.exports: $Exports<'mustache/test/_files/included_tag'>;
}
declare module 'mustache/test/_files/inverted_section.js' {
  declare module.exports: $Exports<'mustache/test/_files/inverted_section'>;
}
declare module 'mustache/test/_files/keys_with_questionmarks.js' {
  declare module.exports: $Exports<'mustache/test/_files/keys_with_questionmarks'>;
}
declare module 'mustache/test/_files/malicious_template.js' {
  declare module.exports: $Exports<'mustache/test/_files/malicious_template'>;
}
declare module 'mustache/test/_files/multiline_comment.js' {
  declare module.exports: $Exports<'mustache/test/_files/multiline_comment'>;
}
declare module 'mustache/test/_files/nested_dot.js' {
  declare module.exports: $Exports<'mustache/test/_files/nested_dot'>;
}
declare module 'mustache/test/_files/nested_higher_order_sections.js' {
  declare module.exports: $Exports<'mustache/test/_files/nested_higher_order_sections'>;
}
declare module 'mustache/test/_files/nested_iterating.js' {
  declare module.exports: $Exports<'mustache/test/_files/nested_iterating'>;
}
declare module 'mustache/test/_files/nesting_same_name.js' {
  declare module.exports: $Exports<'mustache/test/_files/nesting_same_name'>;
}
declare module 'mustache/test/_files/nesting.js' {
  declare module.exports: $Exports<'mustache/test/_files/nesting'>;
}
declare module 'mustache/test/_files/null_string.js' {
  declare module.exports: $Exports<'mustache/test/_files/null_string'>;
}
declare module 'mustache/test/_files/null_view.js' {
  declare module.exports: $Exports<'mustache/test/_files/null_view'>;
}
declare module 'mustache/test/_files/partial_array_of_partials_implicit.js' {
  declare module.exports: $Exports<'mustache/test/_files/partial_array_of_partials_implicit'>;
}
declare module 'mustache/test/_files/partial_array_of_partials.js' {
  declare module.exports: $Exports<'mustache/test/_files/partial_array_of_partials'>;
}
declare module 'mustache/test/_files/partial_array.js' {
  declare module.exports: $Exports<'mustache/test/_files/partial_array'>;
}
declare module 'mustache/test/_files/partial_empty.js' {
  declare module.exports: $Exports<'mustache/test/_files/partial_empty'>;
}
declare module 'mustache/test/_files/partial_template.js' {
  declare module.exports: $Exports<'mustache/test/_files/partial_template'>;
}
declare module 'mustache/test/_files/partial_view.js' {
  declare module.exports: $Exports<'mustache/test/_files/partial_view'>;
}
declare module 'mustache/test/_files/partial_whitespace.js' {
  declare module.exports: $Exports<'mustache/test/_files/partial_whitespace'>;
}
declare module 'mustache/test/_files/recursion_with_same_names.js' {
  declare module.exports: $Exports<'mustache/test/_files/recursion_with_same_names'>;
}
declare module 'mustache/test/_files/reuse_of_enumerables.js' {
  declare module.exports: $Exports<'mustache/test/_files/reuse_of_enumerables'>;
}
declare module 'mustache/test/_files/section_as_context.js' {
  declare module.exports: $Exports<'mustache/test/_files/section_as_context'>;
}
declare module 'mustache/test/_files/simple.js' {
  declare module.exports: $Exports<'mustache/test/_files/simple'>;
}
declare module 'mustache/test/_files/string_as_context.js' {
  declare module.exports: $Exports<'mustache/test/_files/string_as_context'>;
}
declare module 'mustache/test/_files/two_in_a_row.js' {
  declare module.exports: $Exports<'mustache/test/_files/two_in_a_row'>;
}
declare module 'mustache/test/_files/two_sections.js' {
  declare module.exports: $Exports<'mustache/test/_files/two_sections'>;
}
declare module 'mustache/test/_files/unescaped.js' {
  declare module.exports: $Exports<'mustache/test/_files/unescaped'>;
}
declare module 'mustache/test/_files/whitespace.js' {
  declare module.exports: $Exports<'mustache/test/_files/whitespace'>;
}
declare module 'mustache/test/_files/zero_view.js' {
  declare module.exports: $Exports<'mustache/test/_files/zero_view'>;
}
declare module 'mustache/test/context-test.js' {
  declare module.exports: $Exports<'mustache/test/context-test'>;
}
declare module 'mustache/test/helper.js' {
  declare module.exports: $Exports<'mustache/test/helper'>;
}
declare module 'mustache/test/mustache-spec-test.js' {
  declare module.exports: $Exports<'mustache/test/mustache-spec-test'>;
}
declare module 'mustache/test/parse-test.js' {
  declare module.exports: $Exports<'mustache/test/parse-test'>;
}
declare module 'mustache/test/render-test.js' {
  declare module.exports: $Exports<'mustache/test/render-test'>;
}
declare module 'mustache/test/scanner-test.js' {
  declare module.exports: $Exports<'mustache/test/scanner-test'>;
}
declare module 'mustache/test/writer-test.js' {
  declare module.exports: $Exports<'mustache/test/writer-test'>;
}
