// flow-typed signature: b2bd0e9620d39c0cf7c573936cbb6134
// flow-typed version: <<STUB>>/pretty-format_v^23.6.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pretty-format/build-es5/index' {
  declare module.exports: any;
}

declare module 'pretty-format/build/collections' {
  declare module.exports: any;
}

declare module 'pretty-format/build/index' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/asymmetric_matcher' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/convert_ansi' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/dom_collection' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/dom_element' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/immutable' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/lib/escape_html' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/lib/markup' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/react_element' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/react_test_component' {
  declare module.exports: any;
}

declare module 'pretty-format/perf/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pretty-format/build-es5/index.js' {
  declare module.exports: $Exports<'pretty-format/build-es5/index'>;
}
declare module 'pretty-format/build/collections.js' {
  declare module.exports: $Exports<'pretty-format/build/collections'>;
}
declare module 'pretty-format/build/index.js' {
  declare module.exports: $Exports<'pretty-format/build/index'>;
}
declare module 'pretty-format/build/plugins/asymmetric_matcher.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/asymmetric_matcher'>;
}
declare module 'pretty-format/build/plugins/convert_ansi.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/convert_ansi'>;
}
declare module 'pretty-format/build/plugins/dom_collection.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/dom_collection'>;
}
declare module 'pretty-format/build/plugins/dom_element.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/dom_element'>;
}
declare module 'pretty-format/build/plugins/immutable.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/immutable'>;
}
declare module 'pretty-format/build/plugins/lib/escape_html.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/lib/escape_html'>;
}
declare module 'pretty-format/build/plugins/lib/markup.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/lib/markup'>;
}
declare module 'pretty-format/build/plugins/react_element.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/react_element'>;
}
declare module 'pretty-format/build/plugins/react_test_component.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/react_test_component'>;
}
declare module 'pretty-format/perf/test.js' {
  declare module.exports: $Exports<'pretty-format/perf/test'>;
}
