// flow-typed signature: fd7941f8124c64a9c4fc0bd9286175fb
// flow-typed version: <<STUB>>/youch_v^2.0.9/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'youch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'youch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'youch/src/Youch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'youch/src/Youch.js' {
  declare module.exports: $Exports<'youch/src/Youch'>;
}
