// flow-typed signature: c6a43c56f051ebf057a83810409c6c8f
// flow-typed version: <<STUB>>/youch-terminal_v^1.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'youch-terminal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'youch-terminal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'youch-terminal/index' {
  declare module.exports: $Exports<'youch-terminal'>;
}
declare module 'youch-terminal/index.js' {
  declare module.exports: $Exports<'youch-terminal'>;
}
